In [5]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.shape) 


(2, 2, 3)


In [7]:
v=a[:,0,0]

print(v)

[1 7]


In [10]:
v=a[:,0,:]
print(v)

[[1 2 3]
 [7 8 9]]


In [13]:
c=np.arange(1,25).reshape(2,3,4)
print(c)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
